### ISSUE TITLE
Possible to create an iTerm variant of this theme?

### ISSUE THREAD

**Issue by chrisetheridge** [waymondo/apropospriate-theme#10]
I absolutely love this theme for Emacs, and would love an iTerm variant of the theme.

**Comment by waymondo** [comment]
I don't personally use iTerm or know how its themed, but I'm guessing it would be easy enough to just copy the color palette from these values: https://github.com/waymondo/apropospriate-theme/blob/master/apropospriate.el#L33-L81

**Comment by chrisetheridge** [comment]
Oh yes of course! I wasn't looking at that file or iTerm properly! Thank you!
