### ISSUE TITLE
Eager macro-expansion failure

### ISSUE THREAD

**Issue by agsdot** [waymondo/apropospriate-theme#11]
Hi @waymondo,

Thanks for creating a terrific theme. I really like the color scheme for web-mode / html-mode . Really nice color contrasts.

On installing apropospriate-theme with use-package and also with require statements I get "Eager macro-expansion failure: (error "Lisp nesting exceeds `max-lisp-eval-depth'").

On following advice in this [SO article](https://stackoverflow.com/questions/11807128/emacs-nesting-exceeds-max-lisp-eval-depth) and putting in (setq max-lisp-eval-depth 10000) prior to where I put the use-package apropospriate statement I get "Eager macro-expansion failure: (error "Variable binding depth exceeds max-specpdl-size").

The error/warning messages don't seem to impact functionality of the theme, other than slowing down the startup of emacs. I'd like to get rid of that slowdown in my personal emacs.d setup. Do you have any advice?

**Comment by manuel-uberti** [comment]
Yes, I have this error too.

**Comment by waymondo** [comment]
Thanks for reporting, this should be fixed now.

**Comment by agsdot** [comment]
Thanks @waymondo . It works just fine now. Thanks!

**Comment by manuel-uberti** [comment]
Thank you.
