### ISSUE TITLE
Better ediff support

### ISSUE THREAD

**Issue by houli** [waymondo/apropospriate-theme#14]
The current colours in ediff make it nearly impossible to read the right hand side of the diff. I've attached a screenshot which shows off some of the problems. Thanks!
<img width="1360" alt="screen shot 2016-08-11 at 22 31 38" src="https://cloud.githubusercontent.com/assets/143868/17613573/ba1195b6-6013-11e6-988f-2ab06a197ef6.png">

**Comment by waymondo** [comment]
Yuck, yeah that looks bad. I don't personally use `ediff` and its crashing for me as I'm trying to enable it right now. Do you want to open a PR with this support? Here are similar diff styles for reference on to make it seamless:

https://github.com/waymondo/apropospriate-theme/blob/master/apropospriate.el#L310-L326
https://github.com/waymondo/apropospriate-theme/blob/master/apropospriate.el#L375-L382

**Comment by houli** [comment]
Yeah I can take a look at doing this

**Comment by idoo** [comment]
@houli are you ok?)
