### ISSUE TITLE
add better support for org links

### ISSUE THREAD

**Issue by ninrod** [waymondo/apropospriate-theme#15]
as of now an org-link is undistinguishable from a normal word. sample attached (using light theme)

awesome work by the way.

![aproprospriate-light-orglink](https://cloud.githubusercontent.com/assets/8352747/20397108/aa017610-accf-11e6-993e-399aebaa22f9.png)

**Comment by waymondo** [comment]
Thanks for the report, but I'm having trouble reproducing this. Here's a screenshot of me opening an `org-capture` buffer and inserting some text alongside plain text:
![image](https://cloud.githubusercontent.com/assets/923418/20411544/f2525374-acef-11e6-83c0-b3950631b311.png)

Is it possible 'white this is not' is also part of the link? If you call `M-x describe-face` above a character in both pieces of text, what does it tell you?

**Comment by ninrod** [comment]
`sp-show-pair-match-face` and `org-level-1`

what? there's something strange here. I'll try to deactivate smartparens and see what I got.

edit: with smartparens off, I got org-link and org-level-1.

**Comment by ninrod** [comment]
I think that if you open an empty org document and add a single bullet with an org-link in it you will be able to reproduce the screenshot I uploaded above. You must have a different org-capture setup than me, one that does not include a leve 1 org bullet as a template.

**Comment by waymondo** [comment]
Gotcha. The issue was that `org-level-1` inherits from `outline-1` which was the same color as `link`. Changed that here: https://github.com/waymondo/apropospriate-theme/commit/692621d08ca85605ea4c1a1c4c7739d8bf339e76
