### ISSUE TITLE
Better support for avy

### ISSUE THREAD

**Issue by rlazo** [waymondo/apropospriate-theme#16]
[Avy](https://github.com/abo-abo/avy) let you navigate faster. In apropospriate-dark (I haven't tested in light) the background and the color of the shortcut chars added by avy are exactly the same as the text, so it's very hard to use

![screenshot](https://cloud.githubusercontent.com/assets/368578/20440080/9d339e8c-ada5-11e6-934d-367e0cc64cdb.png)

I can reproduce this behavior when running `emacs -q` and loading the packages directly.

Thanks!

**Comment by waymondo** [comment]
What version of avy are you using? I have avy support built-in (my avy version is 0.4.0 from MELPA). This is how it looks (`avy-background` is `t`):

![image](https://cloud.githubusercontent.com/assets/923418/20441446/8d19f0ea-ad92-11e6-91fe-3f27ba01f233.png)

Its possible you are using an older version of `avy` with different face names. What does the const `avy-lead-faces` eval to?

**Comment by rlazo** [comment]
Avy-version: 0.4.0 (Package-Version: 20160814.250)

emacs: 25.1.50.1

emacs -q

> M-x package-initialize
> M-x load-library avy
> M-x set-variable RET avy-background RET t
> M-x load-theme apropospriate-dark

Same result as shown in the screenshot

**Comment by skovuri41** [comment]
i see the same issue on 
GNU Emacs 25.1.1 (x86_64-apple-darwin16.1.0, Carbon Version 157 AppKit 1504.6) of 2016-11-18
Avy-version: 0.4.0 (Package-Version: 20160814.250)

**Comment by skovuri41** [comment]
from spacemacs theme:

;;;;; avy

```
     `(avy-lead-face   ((,class (:background ,blue-bg :foreground ,magenta))))
     `(avy-lead-face-0 ((,class (:background ,blue-bg :foreground ,blue))))
     `(avy-lead-face-1 ((,class (:background ,blue-bg :foreground ,magenta))))
     `(avy-lead-face-2 ((,class (:background ,blue-bg :foreground ,blue))))

```

I tested after making change as follows to verify  and seems to work fine .
however will need to pick the right colors per the theme. 

```
`(avy-lead-face ((,class (:foreground ,orange :weight bold))))
                                       `(avy-lead-face-0 ((,class (:foreground ,orange :weight bold))))
                                       `(avy-lead-face-1 ((,class (:foreground ,orange :weight bold))))
                                       `(avy-lead-face-2 ((,class (:foreground ,orange :weight bold))))
```

**Comment by waymondo** [comment]
found the source of the issue, thanks for reporting.
