### ISSUE TITLE
consider making the cursor a vertical bar in evil insert state by default

### ISSUE THREAD

**Issue by ninrod** [waymondo/apropospriate-theme#17]
Evil users are used to have a vertical bar as a cursor shape in insert state. the hbar is reserved for replace state, usually. 

I had to write this on my init.el: 

```emacs-lisp
(load-theme 'apropospriate-light t)

  ;; ;; fix cursor shape
  (setq evil-insert-state-cursor 'bar)
```

ps: I'm the [reddit thread](https://www.reddit.com/r/emacs/comments/5dgk6c/github_waymondoapropospriatetheme_a_colorful/) starter by the way: /u/Eldrik  o/

**Comment by waymondo** [comment]
I haven't used evil in a long time, and I forget the typical cursor conventions so I'll take your word for it:
https://github.com/waymondo/apropospriate-theme/commit/aa36e3d71d0d61135f70fac650d3d4be19b5ca35

This seems to coincide with Spacemacs as well: https://github.com/syl20bnr/spacemacs/blob/b7e51d70aa3fb81df2da6dc16d9652a002ba5e6b/layers/%2Bspacemacs/spacemacs-evil/packages.el

Thanks for the reddit post!
