### ISSUE TITLE
How do you feel about org-block backgrounds?

### ISSUE THREAD

**Issue by dakrone** [waymondo/apropospriate-theme#2]
Gah, hit enter too early, sorry.

How do you feel about having a background color for org-blocks? (like `#+BEGIN_SRC` and `#+END_SRC`)

I'm happy to submit a PR if you are okay with them having either a lighter or darker background.

**Comment by waymondo** [comment]
Sure, I haven't used org-blocks hence the omission. As long as you can get by using the existing color set and conventions, please feel free to open a PR and I'll merge it in.

**Comment by waymondo** [comment]
Also noted and addressed: https://github.com/waymondo/apropospriate-theme/issues/5#issuecomment-108998663
