### ISSUE TITLE
apropospriate-light in Magit use focus background color of dark theme

### ISSUE THREAD

**Issue by smonff** [waymondo/apropospriate-theme#23]
This bug is about the light version of apropospriate-theme only. 

In Magit, the background-color used of focused items seems to be not so appropriate.  Here is a screenshot.

![ap_magit](https://cloud.githubusercontent.com/assets/1219097/22112612/da78d278-de63-11e6-818a-883229d01f50.png)
Actualy, it seem to use something that would be right in dark version, but we need something lighter for light version.

**Comment by waymondo** [comment]
It looks like it is using the dark version of the highlight color, which I'm not seeing. How are you loading/enabling the theme? Also, what version of magit are you using?

**Comment by smonff** [comment]
I use a package called [theme-changer](https://github.com/hadronzoo/theme-changer) to switch  automatically between light/dark when the time goes. I just tried to disable it and load the theme in a more classical way: 

    (require 'apropospriate)
    (load-theme 'apropospriate-light t)

It don't change the result though.

I am using Magit version `20170118.1927`, Emacs `25.1.1`, gnu/linux.

**Comment by smonff** [comment]
Upgrading Magit to `20170119.1803` fixed it. Sorry for disturbance and thanks for this amazing theme.

**Comment by waymondo** [comment]
Interesting.. I wonder if this was a transient issue with one recent version of magit. `20170118.1927` was quite recent and my version was actually older than that, but it worked before and after upgrading. Anyways, glad you're enjoying the theme!

**Comment by smonff** [comment]
Finally it came back after some time :( 

I'll investigate more, leave the bug closed because I have no evidence it is related to the theme itself as you don't experiment the same.
