### ISSUE TITLE
Git Messenger

### ISSUE THREAD

**Issue by idoo** [waymondo/apropospriate-theme#24]
It would be nice to fix support Git Messenger

https://github.com/syohex/emacs-git-messenger

For now it looks sometimes wrong — http://take.ms/gqZPeH

**Comment by waymondo** [comment]
That looks like an issue with the positioning of [`popup`](https://github.com/auto-complete/popup-el) in your setup. This is how it should look when correctly positioned: 
https://www.dropbox.com/s/z000hpit95w1zlv/Screenshot%202017-03-22%2011.33.46.png?dl=0

You can see that the popup is correctly styled in your screenshot then. There are a handful of known display issues with the popup library, so take a look at the [issues over there](https://github.com/auto-complete/popup-el/issues).
