### ISSUE TITLE
dired-directory not set

### ISSUE THREAD

**Issue by matthewbauer** [waymondo/apropospriate-theme#25]
In my configuration "dired-directory" is not being set to the right color.

Without ido, "dired-directory" can't inherit from ido-subdir.  To fix this, I use this configuration:

```
(defface ido-subdir  '((((min-colors 88) (class color))
                        :foreground "red1")
                       (((class color))
                        :foreground "red")
                       (t :underline t))
  "Face used by Ido for highlighting subdirs in the alternatives."
  :group 'ido)

(use-package apropospriate-theme
  :demand
  :config
  (load-theme 'apropospriate-dark))
```

As a fix for this, I suggest swapping ido-subdir and dired-directory so ido-subdir inherits from sired-directory.

**Comment by waymondo** [comment]
Thanks for pointing this out, I've updated so that `ido` being loaded isn't a requirement.
