### ISSUE TITLE
Make a stable release to be included in MELPA stable

### ISSUE THREAD

**Issue by matthewbauer** [waymondo/apropospriate-theme#26]
Hi,

I've been using apropospriate regularly now and it seems stable. Can you make a versioned release so that it can be included in the MELPA stable set?

**Comment by waymondo** [comment]
I've tagged the latest commit as `0.1.0` but I don't see it showing up on MELPA stable. Are you familiar enough with MELPA stable to know what I'm missing?

**Comment by matthewbauer** [comment]
It looks like it's here now:

http://stable.melpa.org/#/apropospriate-theme
