### ISSUE TITLE
Error when loading the theme: (void-variable variant)

### ISSUE THREAD

**Issue by dgutov** [waymondo/apropospriate-theme#3]
``` el
Debugger entered--Lisp error: (void-variable variant)
  (eq variant (quote light))
  (if (eq variant (quote light)) (quote (("#FF5722" . 0) ("#FFA000" . 10) ("#FFD600" . 30) ("#f2f2f2" . 60) ("#FAFAFA" . 80))) (quote (("#F8BBD0" . 0) ("#EC407A" . 10) ("#B388FF" . 30) ("#f2f2f2" . 60) ("#FAFAFA" . 80))))
  eval((if (eq variant (quote light)) (quote (("#FF5722" . 0) ("#FFA000" . 10) ("#FFD600" . 30) ("#f2f2f2" . 60) ("#FAFAFA" . 80))) (quote (("#F8BBD0" . 0) ("#EC407A" . 10) ("#B388FF" . 30) ("#f2f2f2" . 60) ("#FAFAFA" . 80)))))
  custom-theme-recalc-variable(highlight-tail-colors)
```

**Comment by waymondo** [comment]
how are you loading the theme? trying to reproduce this.

**Comment by dgutov** [comment]
Install the theme from MELPA, then, in the same session, `M-x load-theme`, and pick one of the two variants of this theme.

**Comment by dgutov** [comment]
Guess I should also mention that I'm using the Emacs master.

**Comment by waymondo** [comment]
Odd - I just removed the package, restarted, and did `M-x package-install` then `M-x load-theme` and chose each version and it loaded correctly. I _think_ I'm on a very recent version of Emacs. When I do `C-h C-a` I get `GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.3.0, NS appkit-1347.57 Version 10.10.3 (Build 14D130a))`

If you eval `(load-theme 'apropospriate-light t)` afterwards does it load?

**Comment by dgutov** [comment]
> If you eval (load-theme 'apropospriate-light t) afterwards does it load?

That makes no difference.

The error is in `highlight-tail-colors` value expression. If I replace `variant` with `',variant`, that gets rid of the error. Could it be that you're not seeing the error because you don't have `highlight-tail` installed?

**Comment by waymondo** [comment]
Yes, you are the man. I have `highlight-tail` disabled currently but that was definitely the issue. Fixed and pushed.

**Comment by dgutov** [comment]
Yup, it's fixed. Thanks.
