### ISSUE TITLE
Support for ledger-mode

### ISSUE THREAD

**Issue by ptkab** [waymondo/apropospriate-theme#38]
Does this theme support ledger-mode out of the box? If not, is it possible to add support for that?

This is a great theme btw!

**Comment by waymondo** [comment]
I haven't used `ledger-mode` before, but if you are comfortable with emacs-lisp, feel free to open a PR with support for the necessary faces.

**Comment by ptkab** [comment]
Cool. I am not super comfortable with `elisp` at the time of writing this, but I am learning it. Let me try if I can add the faces and I will open a PR once done!
