### ISSUE TITLE
Highlight line on Org Agenda not appearing

### ISSUE THREAD

**Issue by cantao** [waymondo/apropospriate-theme#43]
Hi!

Thanks a lot, that is the most beautiful theme I've ever seen!

But there is a small quirk: the highlight line on Org Agenda does not appear. The cursor color also changes randomly, sometimes is red, sometimes is the same color as the background.

I tried figuring it out by myself but there are one million variables to control the colors. Which one should I change???

I'm using Doom Emacs 29.3 on Archlinux.

Thank you very much!

**Comment by waymondo** [comment]
hi there, i'm not an org agenda user, but the current line is highlighted for me when i have `global-hl-line-mode` enabled:

![image](https://github.com/waymondo/apropospriate-theme/assets/923418/0334b95f-0e09-415b-9071-6d32cf013670)
![image](https://github.com/waymondo/apropospriate-theme/assets/923418/172d27cb-feb3-43db-a889-5b86cd03d5ea)

regarding the cursor changing colors, i'm not sure what to attribute that to but it shouldn't be this theme. i'm not a doom emacs user, so maybe it has to do with some package or configuration within that?

**Comment by cantao** [comment]
Hi! I have `global-hl-line-mode` enabled, but I tested it anyway. Enabling or disabling it changes nothing. I realized that hovering the mouse highlights the entries, but not with the keyboard (heavy keyboard user here :smile:).

I have just noticed another interesting thing: the font on the modeline gets tiny on the agenda, or when the Emacs window looses focus.

- Regular modeline:
![regular](https://github.com/waymondo/apropospriate-theme/assets/3270516/20e4dfae-c77f-47fc-8cb3-99d58209a09d)
- Unfocused window modeline:
![weird](https://github.com/waymondo/apropospriate-theme/assets/3270516/35e3d9bb-96b6-4979-9e98-4106f4a27ac6)
- Agenda modeline:
![agenda](https://github.com/waymondo/apropospriate-theme/assets/3270516/ca489349-ef67-484b-8eb9-7a6f6eef8f2a)



Anyway, it´s probably some Doom weirdness...

I'm going to close it for now. If I figure something out I'll create a PR.

Thank you very much!

**Comment by cantao** [comment]
Ok, couldn't resist tweaking it and...

1. The problem with the varying modeline size is that apropospriate-theme changes the font size, confusing the Doom modeline. In order to avoid font resize, add the following snippet to `doom/config.el`:
   ```elisp
   (use-package! apropospriate-theme
     :ensure t
     :config
     (setq apropospriate-mode-line-height nil)
     (load-theme 'apropospriate-light t))

   ```
2. Doom uses [solaire-mode](https://github.com/hlissner/emacs-solaire-mode), which makes some colors brighter to visually distinguish editing buffers and temporary ones (like the Org Agenda buffer!). In order to disable it, add the following snippet to `doom/config.el` **after** loading the theme (item 1 above):
   ```elisp
   (after! solaire-mode
     (solaire-global-mode -1))

   ```

Ta-dah! 🥳
