### ISSUE TITLE
Background color for the source code example being edited too light

### ISSUE THREAD

**Issue by joonro** [waymondo/apropospriate-theme#5]
Hi,

Thank you for the great theme. One thing I noticed is that when I edit an [source code example](http://orgmode.org/manual/Literal-examples.html) with `C-c '`, the background color for the block being edited becomes yellow, which is too bright for the dark theme:

![image](https://cloud.githubusercontent.com/assets/1063143/7976561/bd6befb0-0a31-11e5-9cd4-40d5de5e499e.png)

Would it be possible to change this to a more subdued color?

**Comment by waymondo** [comment]
Thanks, this was also noted in #2. I just pushed a commit so that horrendous yellow color doesn't show when editing the org-mode code blocks. I don't use org-mode with code blocks personally so let me know if you notice anything else could be improved.

**Comment by joonro** [comment]
I did notice another thing - I will open an issue for that soon. Thank you so much.
