### ISSUE TITLE
org-mode columnview background color is too light

### ISSUE THREAD

**Issue by joonro** [waymondo/apropospriate-theme#6]
Hi,

Another thing was the background color for org-mode columnview is too light so it is hard to see:

![image](https://cloud.githubusercontent.com/assets/1063143/7996748/b87b21c2-0ad8-11e5-8fda-4c5638476b0e.png)

Thank you so much!

**Comment by waymondo** [comment]
Can you supply me with your source? I'm also unfamiliar with org-mode columns, but this will be an easy fix.

**Comment by joonro** [comment]
Sure.

``` org-mode
* Playground
** Item 1
** Item 2
```

You will see the columnview by pressing `C-c C-x C-c` with cursor on the `* Playground`.

Thank you so much!

**Comment by waymondo** [comment]
Cool, thanks. Done.
