### ISSUE TITLE
Marked region is not very clear with hl-line-mode (dark-theme)

### ISSUE THREAD

**Issue by Gleek** [waymondo/apropospriate-theme#7]
Marking the region in the current line while hl-line-mode is active, gives the mark a color which is very similar to the current line, making it very difficult to recognize.
The situation is better when it comes to the light version of the theme. But gets a little problematic on the dark version.
Support for hl-line-mode would be helpful
![screen shot 2015-08-18 at 12 54 45 pm](https://cloud.githubusercontent.com/assets/3756804/9324475/613e770a-45a8-11e5-83ed-49e745fc50cc.png)

**Comment by waymondo** [comment]
Thanks for the feedback, I see what you mean and I increased the contrast between these variants.

**Comment by Gleek** [comment]
Thanks. Looks better. Great work!
